name: MultiAgentCopilot
metadata:
    template: azd-init@1.5.1
hooks:
    postdeploy:
      shell: pwsh
      continueOnError: false
      interactive: true
      run: ./azd-hooks/postdeploy.ps1  # Adjust path since azure.yaml is inside /csharp
services:
    ChatServiceWebApi:
        project: ./src/ChatAPI   # Relative to /csharp
        host: containerapp
        language: csharp
        docker:
            path: ./src/ChatAPI/Dockerfile   # Ensure correct Dockerfile path
    FrontendApp:
        project: ../frontend  # Move up one level to access frontend
        host: containerapp
        image: frontend  # Specify image name to avoid needing a language
        docker:
            path: ../frontend/Dockerfile  # Move up to correct Dockerfile path
